### ISSUE TITLE
Maintaining Completing bp-profile-completion

### ISSUE THREAD

**Issue by restyles4** [buddydev/bp-profile-completion#1]
Greetings:
bp-profile-completion does not work when a payment gateway is called. bp-profile-completion interrupts the request for email functionality as well. Making your plug-in useless in most circumstances except for non-auto-response user setup scenarios. 

While your efforts are well appreciated in DEV of this plugin thus far, "your release of it without support or basic use as claimed" by you is contradictory to GitHub and Wordpress Depository Policy. Furthermore is disingenuous to the DEV community.   

Do you have any intention on being honest about finishing your plugin DEV efforts?

**Comment by sbrajesh** [comment]
Are you serious? What makes it dangerous? 
Please do not assume things just because you want to.

1. It is supported over BuddyDev forums. Have you posted in our forums?
2. Say for example, we did not support it, It will be our call and not others. How does that make it dangerous?

3. It can not and does not stop email. Show me the place where we are stopping any email in this plugin?

4. The plugin clearly mentions that if a user does not have profile fields complete(as enabled in settings), They will be limited  to profile(if you enable the restriction).

We created it for plain BuddyPress sites and we did not advertise compatibility for any 3rd party plugin.

It is a free plugin and you are free to fork it and submit any 3rd party compatibility/enhancements. We do not have free time to work on all the possible plugin conflicts. If it comes to our notice and we have available time, we do take care of that.

Here is the link that shows how to get support.
https://wordpress.org/plugins/buddypress-profile-completion/#where%20do%20i%20get%20support%3F

I hope we have a more constructive discussion in future.

Regards
Brajesh
